<div class="container">
  <div class="row">

    <div class="col text-center">
      <h2>Créér un utilisateur</h2>
    </div>

    <div class="col-12">
        <div class="form-group">
          <%= form_tag url_for(action: 'create'), method: "post" do %>  
            <%= label_tag 'first_name' %>
            <%= text_area_tag 'first_name', @user.first_name, class: 'form-control' %>
            <br />
            <%= label_tag 'last_name' %>
            <%= text_area_tag 'last_name', @user.last_name, class: 'form-control' %>
            <br />
            <%= label_tag 'Email' %>
            <%= text_field_tag 'email', @user.email, class: 'form-control' %>
            <br />
            <%= label_tag 'Mot de passe' %>
            <%= text_area_tag 'password', @user.password, class: 'form-control' %>
            <br />                             
            <%= label_tag 'city' %>
            <%= text_area_tag 'city_name', @user.city_id, class: 'form-control' %>
            <br />
            <%= label_tag 'Description' %>
            <%= text_area_tag 'description', @user.description, class: 'form-control' %>
            <br />
            <%= label_tag 'Age' %>
            <%= text_area_tag 'age', @user.age, class: 'form-control' %>
            <br />
            <%= submit_tag "Inscription !", class: 'btn btn-success' %>
          <% end %>
        </div>

        <!-- affiche les erreurs qui empêchent la création du nouveau potin -->
        <% if @user.errors.any? %>
          <div class="alert alert-warning mt-2" role="alert">
            <p>Nous navons pas réussi à créer d'utilisateur pour la (ou les) raison(s) suivante(s) :</p>
              <ul>
                <% @user.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
              <p>Merci de réessayer</p>
        <% end %>
        </div>

    </div>
  </div>
</div>